### ISSUE TITLE
Screws/nuts for idlers collide Nema23 motor

### ISSUE THREAD

**Issue by eras** [shapeoko/Shapeoko_2#1]
This picture should make my trouble pretty clear: 
![shapeoko2_nema23](https://f.cloud.github.com/assets/1159374/1414301/2400a9be-3e78-11e3-82a3-098fee349f04.png)

I suppose it'd be a much better solution to move the holes a bit than to add a new set of holes or use spacers of some sort.

**Comment by shapeoko** [comment]
In order to work around this, I used button head screws for the smooth idlers (the head is much shorter than the socket head cap screw), with the head on the outside of the plate. Then, use spacers between the nema23 and the plate. I chose 1/8" (3.175mm) aluminum spacers with a #12 bore (5.5mm).

**Comment by eras** [comment]
I don't yet have a Shapeoko2, as I believe is the case for most ;-), but maybe this could be fixed for the current preorder? But yes, that workaround works.

Edit: I looked that it has 4.13 mm space to move and it should move at least 3.43 mm, assuming cad pictures are precise, tight spot :). But at least the numbers say it is more annoying to add another hole once I receive the plate, because it would necessarily overlap the old one.

**Comment by shapeoko** [comment]
I should have been more precise in my last reply. The smooth idlers are in their location by design. nema23 motors  will mount without interference by using spacers to stand them off from the plate. The nema23s can't sit flush against the plate because of the size of the boss. if you try to mount the nema 23s without spacers, you will bend the plate around the boss, regardless of where the smooth idlers are.
